import { NextResponse } from "next/server"

export async function GET() {
  // Mock marketplace items (in production, fetch from database/API)
  const items = [
    {
      id: "1",
      name: "Okta Integration",
      type: "integration",
      description: "Connect Okta for identity and access management",
      vendor: "Okta",
      category: "Identity",
      downloads: 1250,
      rating: 4.8,
      installed: false,
      version: "2.1.0",
      updated_at: "2025-01-10T00:00:00Z",
    },
    {
      id: "2",
      name: "AWS CloudTrail",
      type: "integration",
      description: "Ingest AWS CloudTrail logs for security monitoring",
      vendor: "Amazon Web Services",
      category: "Cloud",
      downloads: 2100,
      rating: 4.9,
      installed: true,
      version: "3.0.1",
      updated_at: "2025-01-12T00:00:00Z",
    },
    {
      id: "3",
      name: "CrowdStrike Falcon",
      type: "integration",
      description: "Endpoint detection and response integration",
      vendor: "CrowdStrike",
      category: "EDR",
      downloads: 1800,
      rating: 4.7,
      installed: false,
      version: "1.5.2",
      updated_at: "2025-01-08T00:00:00Z",
    },
    {
      id: "4",
      name: "Log4j Exploit Detection",
      type: "rule",
      description: "Detect Log4Shell exploitation attempts",
      category: "Vulnerability",
      downloads: 5200,
      rating: 4.9,
      installed: true,
      version: "1.2.0",
      updated_at: "2024-12-15T00:00:00Z",
    },
    {
      id: "5",
      name: "Phishing Kit Detection",
      type: "rule",
      description: "Identify phishing infrastructure and campaigns",
      category: "Email Security",
      downloads: 3400,
      rating: 4.6,
      installed: false,
      version: "2.0.0",
      updated_at: "2025-01-05T00:00:00Z",
    },
    {
      id: "6",
      name: "Ransomware Response",
      type: "playbook",
      description: "Automated ransomware detection and containment",
      category: "Incident Response",
      downloads: 2800,
      rating: 4.8,
      installed: true,
      version: "1.3.0",
      updated_at: "2025-01-01T00:00:00Z",
    },
    {
      id: "7",
      name: "DDoS Mitigation",
      type: "playbook",
      description: "Automated DDoS attack detection and mitigation",
      category: "Network Security",
      downloads: 1900,
      rating: 4.5,
      installed: false,
      version: "1.1.0",
      updated_at: "2024-12-20T00:00:00Z",
    },
  ]

  return NextResponse.json(items)
}
