import { NextResponse } from "next/server"

export async function GET() {
  // Mock data - in production, this would query your database
  const controls = [
    {
      id: "1",
      control_id: "NIST AC-2",
      framework: "NIST 800-53",
      title: "Account Management",
      status: "failing",
      evidence: [
        {
          source: "SIEM Log",
          result: "Login without MFA detected",
          timestamp: new Date(Date.now() - 1000 * 60 * 15),
          details: "User admin@company.com logged in without MFA from 192.168.1.100",
        },
        {
          source: "Okta API",
          result: "MFA enforced for 87% of users",
          timestamp: new Date(Date.now() - 1000 * 60 * 30),
        },
      ],
      checks_passing: 2,
      checks_total: 7,
      last_checked: new Date(Date.now() - 1000 * 60 * 5),
      assigned_to: "security-team",
      priority: "critical",
      remediation_playbook: "enforce-mfa",
    },
    {
      id: "2",
      control_id: "PCI 7.1",
      framework: "PCI DSS",
      title: "Limit access to system components",
      status: "failing",
      evidence: [
        {
          source: "AWS API",
          result: "S3 bucket 'customer-data' is publicly accessible",
          timestamp: new Date(Date.now() - 1000 * 60 * 45),
          details: "Bucket policy allows public read access",
        },
      ],
      checks_passing: 3,
      checks_total: 5,
      last_checked: new Date(Date.now() - 1000 * 60 * 10),
      assigned_to: "cloud-team",
      priority: "critical",
      remediation_playbook: "secure-s3-bucket",
    },
    {
      id: "3",
      control_id: "PCI 6.1",
      framework: "PCI DSS",
      title: "Security vulnerability management",
      status: "partial",
      evidence: [
        {
          source: "EDR",
          result: "12 endpoints with unpatched CVE-2024-1234",
          timestamp: new Date(Date.now() - 1000 * 60 * 60),
          details: "Critical vulnerability in Windows systems",
        },
        {
          source: "Vulnerability Scanner",
          result: "Patch compliance: 78%",
          timestamp: new Date(Date.now() - 1000 * 60 * 90),
        },
      ],
      checks_passing: 5,
      checks_total: 8,
      last_checked: new Date(Date.now() - 1000 * 60 * 20),
      assigned_to: "patch-team",
      priority: "high",
      remediation_playbook: "patch-deployment",
    },
    {
      id: "4",
      control_id: "NIST IA-4",
      framework: "NIST 800-53",
      title: "Identifier Management",
      status: "partial",
      evidence: [
        {
          source: "Okta",
          result: "3 admin accounts inactive for 90+ days",
          timestamp: new Date(Date.now() - 1000 * 60 * 120),
          details: "Accounts: admin1, admin2, admin3",
        },
      ],
      checks_passing: 4,
      checks_total: 6,
      last_checked: new Date(Date.now() - 1000 * 60 * 15),
      priority: "medium",
    },
    {
      id: "5",
      control_id: "GDPR Art.32",
      framework: "GDPR",
      title: "Security of processing",
      status: "failing",
      evidence: [
        {
          source: "Database Audit",
          result: "Encryption at rest not enabled for 2 databases",
          timestamp: new Date(Date.now() - 1000 * 60 * 180),
          details: "customer_db and analytics_db lack encryption",
        },
      ],
      checks_passing: 2,
      checks_total: 5,
      last_checked: new Date(Date.now() - 1000 * 60 * 30),
      assigned_to: "data-team",
      priority: "critical",
      remediation_playbook: "enable-encryption",
    },
    {
      id: "6",
      control_id: "NIST AU-2",
      framework: "NIST 800-53",
      title: "Audit Events",
      status: "passing",
      evidence: [
        {
          source: "SIEM",
          result: "All required events are being logged",
          timestamp: new Date(Date.now() - 1000 * 60 * 10),
        },
        {
          source: "Log Retention Check",
          result: "Logs retained for 365 days",
          timestamp: new Date(Date.now() - 1000 * 60 * 60),
        },
      ],
      checks_passing: 6,
      checks_total: 6,
      last_checked: new Date(Date.now() - 1000 * 60 * 5),
      priority: "low",
    },
    {
      id: "7",
      control_id: "PCI 8.2",
      framework: "PCI DSS",
      title: "User authentication",
      status: "passing",
      evidence: [
        {
          source: "AD Policy",
          result: "Password complexity requirements met",
          timestamp: new Date(Date.now() - 1000 * 60 * 30),
        },
      ],
      checks_passing: 4,
      checks_total: 4,
      last_checked: new Date(Date.now() - 1000 * 60 * 15),
      priority: "medium",
    },
    {
      id: "8",
      control_id: "HIPAA 164.312(a)(1)",
      framework: "HIPAA",
      title: "Access Control",
      status: "passing",
      evidence: [
        {
          source: "Access Review",
          result: "Role-based access control implemented",
          timestamp: new Date(Date.now() - 1000 * 60 * 45),
        },
      ],
      checks_passing: 5,
      checks_total: 5,
      last_checked: new Date(Date.now() - 1000 * 60 * 20),
      priority: "high",
    },
    {
      id: "9",
      control_id: "UAE PDPL Art.5",
      framework: "UAE Data Protection Law",
      title: "Data Processing Principles",
      status: "partial",
      evidence: [
        {
          source: "Data Inventory",
          result: "Personal data inventory incomplete for 3 systems",
          timestamp: new Date(Date.now() - 1000 * 60 * 60),
          details: "CRM, HR Portal, and Customer Portal missing data mapping",
        },
        {
          source: "Privacy Assessment",
          result: "Data minimization principles applied to 75% of systems",
          timestamp: new Date(Date.now() - 1000 * 60 * 90),
        },
      ],
      checks_passing: 3,
      checks_total: 5,
      last_checked: new Date(Date.now() - 1000 * 60 * 25),
      assigned_to: "privacy-team",
      priority: "high",
      remediation_playbook: "complete-data-inventory",
    },
    {
      id: "10",
      control_id: "NESA CC-1.1",
      framework: "UAE NESA",
      title: "Cybersecurity Governance",
      status: "passing",
      evidence: [
        {
          source: "Policy Review",
          result: "Cybersecurity governance framework established",
          timestamp: new Date(Date.now() - 1000 * 60 * 30),
        },
        {
          source: "Board Minutes",
          result: "Quarterly cybersecurity reports to board",
          timestamp: new Date(Date.now() - 1000 * 60 * 120),
        },
      ],
      checks_passing: 6,
      checks_total: 6,
      last_checked: new Date(Date.now() - 1000 * 60 * 15),
      priority: "medium",
    },
    {
      id: "11",
      control_id: "NESA CC-2.3",
      framework: "UAE NESA",
      title: "Incident Response",
      status: "failing",
      evidence: [
        {
          source: "Incident Response Test",
          result: "Last IR drill conducted 8 months ago (required: quarterly)",
          timestamp: new Date(Date.now() - 1000 * 60 * 240),
          details: "NESA requires quarterly incident response drills",
        },
      ],
      checks_passing: 2,
      checks_total: 5,
      last_checked: new Date(Date.now() - 1000 * 60 * 10),
      assigned_to: "security-team",
      priority: "critical",
      remediation_playbook: "schedule-ir-drill",
    },
    {
      id: "12",
      control_id: "UAE PDPL Art.9",
      framework: "UAE Data Protection Law",
      title: "Data Subject Rights",
      status: "partial",
      evidence: [
        {
          source: "Privacy Portal",
          result: "Data subject access request portal implemented",
          timestamp: new Date(Date.now() - 1000 * 60 * 60),
        },
        {
          source: "Request Tracking",
          result: "Average response time: 35 days (required: 30 days)",
          timestamp: new Date(Date.now() - 1000 * 60 * 180),
          details: "3 requests exceeded the 30-day deadline",
        },
      ],
      checks_passing: 4,
      checks_total: 6,
      last_checked: new Date(Date.now() - 1000 * 60 * 20),
      assigned_to: "privacy-team",
      priority: "high",
      remediation_playbook: "improve-dsar-process",
    },
    {
      id: "13",
      control_id: "DIFC DPL 5.1",
      framework: "DIFC Data Protection",
      title: "Cross-border Data Transfer",
      status: "failing",
      evidence: [
        {
          source: "Data Flow Mapping",
          result: "2 international data transfers lack adequate safeguards",
          timestamp: new Date(Date.now() - 1000 * 60 * 90),
          details: "Transfers to US and India require SCCs or BCRs",
        },
      ],
      checks_passing: 1,
      checks_total: 4,
      last_checked: new Date(Date.now() - 1000 * 60 * 30),
      assigned_to: "legal-team",
      priority: "critical",
      remediation_playbook: "implement-transfer-safeguards",
    },
    {
      id: "14",
      control_id: "NESA CC-3.2",
      framework: "UAE NESA",
      title: "Security Monitoring",
      status: "passing",
      evidence: [
        {
          source: "SIEM",
          result: "24/7 security monitoring operational",
          timestamp: new Date(Date.now() - 1000 * 60 * 5),
        },
        {
          source: "SOC Metrics",
          result: "Mean time to detect: 12 minutes",
          timestamp: new Date(Date.now() - 1000 * 60 * 30),
        },
      ],
      checks_passing: 5,
      checks_total: 5,
      last_checked: new Date(Date.now() - 1000 * 60 * 10),
      priority: "high",
    },
    {
      id: "15",
      control_id: "UAE PDPL Art.12",
      framework: "UAE Data Protection Law",
      title: "Data Breach Notification",
      status: "passing",
      evidence: [
        {
          source: "Breach Response Plan",
          result: "Breach notification procedures documented",
          timestamp: new Date(Date.now() - 1000 * 60 * 45),
        },
        {
          source: "Notification Templates",
          result: "Templates for 72-hour notification ready",
          timestamp: new Date(Date.now() - 1000 * 60 * 60),
        },
      ],
      checks_passing: 4,
      checks_total: 4,
      last_checked: new Date(Date.now() - 1000 * 60 * 15),
      priority: "critical",
    },
  ]

  const stats = {
    total: controls.length,
    passing: controls.filter((c) => c.status === "passing").length,
    failing: controls.filter((c) => c.status === "failing").length,
    partial: controls.filter((c) => c.status === "partial").length,
    unassigned: controls.filter((c) => c.status === "unassigned").length,
    compliance_score: Math.round((controls.filter((c) => c.status === "passing").length / controls.length) * 100),
    critical_gaps: controls.filter((c) => c.status === "failing" && c.priority === "critical").length,
  }

  return NextResponse.json({ controls, stats })
}
