import { NextResponse } from "next/server"

export async function GET() {
  // Simulate real-time compliance data
  const frameworks = [
    {
      framework: "ISO 27001",
      score: 87 + Math.floor(Math.random() * 5),
      trend: 2.3,
      passing: 142,
      failing: 18,
      nonApplicable: 12,
      totalControls: 172,
      lastAudit: "2 hours ago",
    },
    {
      framework: "NIST 800-53",
      score: 92 + Math.floor(Math.random() * 3),
      trend: 1.8,
      passing: 284,
      failing: 21,
      nonApplicable: 15,
      totalControls: 320,
      lastAudit: "1 hour ago",
    },
    {
      framework: "PCI-DSS",
      score: 95 + Math.floor(Math.random() * 2),
      trend: 3.2,
      passing: 112,
      failing: 4,
      nonApplicable: 2,
      totalControls: 118,
      lastAudit: "30 minutes ago",
    },
    {
      framework: "GDPR",
      score: 89 + Math.floor(Math.random() * 4),
      trend: -0.5,
      passing: 78,
      failing: 9,
      nonApplicable: 3,
      totalControls: 90,
      lastAudit: "3 hours ago",
    },
    {
      framework: "HIPAA",
      score: 91 + Math.floor(Math.random() * 3),
      trend: 2.1,
      passing: 156,
      failing: 12,
      nonApplicable: 8,
      totalControls: 176,
      lastAudit: "1 hour ago",
    },
    {
      framework: "CIS Benchmarks",
      score: 88 + Math.floor(Math.random() * 4),
      trend: 1.5,
      passing: 198,
      failing: 24,
      nonApplicable: 10,
      totalControls: 232,
      lastAudit: "45 minutes ago",
    },
    {
      framework: "UAE PDPL",
      score: 90 + Math.floor(Math.random() * 4),
      trend: 2.8,
      passing: 86,
      failing: 8,
      nonApplicable: 4,
      totalControls: 98,
      lastAudit: "1 hour ago",
    },
    {
      framework: "NESA IAS",
      score: 88 + Math.floor(Math.random() * 5),
      trend: 1.9,
      passing: 124,
      failing: 14,
      nonApplicable: 6,
      totalControls: 144,
      lastAudit: "2 hours ago",
    },
    {
      framework: "UAE Cybersecurity Law",
      score: 93 + Math.floor(Math.random() * 3),
      trend: 3.1,
      passing: 67,
      failing: 5,
      nonApplicable: 3,
      totalControls: 75,
      lastAudit: "45 minutes ago",
    },
    {
      framework: "Dubai Data Law",
      score: 91 + Math.floor(Math.random() * 4),
      trend: 2.5,
      passing: 54,
      failing: 4,
      nonApplicable: 2,
      totalControls: 60,
      lastAudit: "1.5 hours ago",
    },
  ]

  return NextResponse.json(frameworks)
}
