import { NextResponse } from "next/server"

export async function GET() {
  // Simulated knowledge base data
  const articles = [
    {
      id: 1,
      title: "Incident Response Procedures for Ransomware",
      description:
        "Comprehensive step-by-step guide for responding to ransomware incidents, including containment strategies, forensic analysis, and recovery procedures.",
      category: "Procedures",
      type: "Guide",
      author: "Security Team",
      authorRole: "Senior Security Analyst",
      updatedAt: "2024-01-30",
      views: 234,
      readTime: 12,
      tags: ["ransomware", "incident-response", "containment"],
      trending: true,
      featured: true,
      rating: 4.8,
      contributors: 3,
    },
    {
      id: 2,
      title: "OT Network Segmentation Best Practices",
      description:
        "Detailed guidelines for implementing network segmentation in operational technology environments to enhance security posture and reduce attack surface.",
      category: "Procedures",
      type: "Guide",
      author: "OT Security Team",
      authorRole: "OT Security Specialist",
      updatedAt: "2024-01-08",
      views: 156,
      readTime: 15,
      tags: ["network-segmentation", "scada", "ot"],
      trending: false,
      featured: true,
      rating: 4.6,
      contributors: 2,
    },
    {
      id: 3,
      title: "Phishing Email Analysis Workflow",
      description:
        "Standard operating procedure for analyzing suspicious emails, identifying phishing indicators, and coordinating response actions across the organization.",
      category: "Articles",
      type: "Workflow",
      author: "SOC Analyst",
      authorRole: "Tier 2 Analyst",
      updatedAt: "2024-01-12",
      views: 189,
      readTime: 8,
      tags: ["phishing", "email", "analysis"],
      trending: true,
      featured: false,
      rating: 4.7,
      contributors: 4,
    },
    {
      id: 4,
      title: "Vulnerability Assessment Methodology",
      description:
        "Complete framework for conducting vulnerability assessments, including scanning procedures, risk prioritization, and remediation tracking.",
      category: "Articles",
      type: "Guide",
      author: "Vulnerability Team",
      authorRole: "Vulnerability Manager",
      updatedAt: "2024-01-05",
      views: 298,
      readTime: 18,
      tags: ["vulnerability", "assessment", "scanning"],
      trending: false,
      featured: true,
      rating: 4.9,
      contributors: 5,
    },
    {
      id: 5,
      title: "Threat Intelligence Integration Guide",
      description:
        "How to effectively integrate threat intelligence feeds into your security operations, including IOC management and automated response workflows.",
      category: "Threat Profiles",
      type: "Guide",
      author: "Threat Intel Team",
      authorRole: "Threat Intelligence Analyst",
      updatedAt: "2024-01-15",
      views: 187,
      readTime: 10,
      tags: ["threat-intel", "iocs", "integration"],
      trending: true,
      featured: false,
      rating: 4.5,
      contributors: 3,
    },
    {
      id: 6,
      title: "Zero Trust Architecture Implementation",
      description:
        "Practical guide to implementing zero trust principles in enterprise environments, covering identity verification, micro-segmentation, and continuous monitoring.",
      category: "Articles",
      type: "Guide",
      author: "Architecture Team",
      authorRole: "Security Architect",
      updatedAt: "2024-01-20",
      views: 342,
      readTime: 22,
      tags: ["zero-trust", "architecture", "identity"],
      trending: true,
      featured: true,
      rating: 4.9,
      contributors: 6,
    },
    {
      id: 7,
      title: "Cloud Security Posture Management",
      description:
        "Best practices for maintaining secure cloud configurations across AWS, Azure, and GCP, including automated compliance checks and remediation.",
      category: "Procedures",
      type: "Checklist",
      author: "Cloud Security Team",
      authorRole: "Cloud Security Engineer",
      updatedAt: "2024-01-25",
      views: 276,
      readTime: 14,
      tags: ["cloud", "cspm", "compliance"],
      trending: true,
      featured: false,
      rating: 4.7,
      contributors: 4,
    },
    {
      id: 8,
      title: "APT Group Tactics and Techniques",
      description:
        "Comprehensive analysis of advanced persistent threat groups, their TTPs, and defensive strategies mapped to the MITRE ATT&CK framework.",
      category: "Threat Profiles",
      type: "Analysis",
      author: "Threat Research Team",
      authorRole: "Senior Threat Researcher",
      updatedAt: "2024-01-18",
      views: 412,
      readTime: 25,
      tags: ["apt", "mitre-attack", "threat-hunting"],
      trending: true,
      featured: true,
      rating: 5.0,
      contributors: 7,
    },
  ]

  return NextResponse.json(articles)
}
