"use client"

import { SidebarNav } from "@/components/sidebar-nav"
import { Header } from "@/components/header"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { ThreatIntelStats } from "@/components/threat-intel-stats"
import { ThreatActorsTable } from "@/components/threat-actors-table"
import { IOCTable } from "@/components/ioc-table"
import { ThreatTrendsChart } from "@/components/threat-trends-chart"
import { ThreatCategoriesChart } from "@/components/threat-categories-chart"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Shield, Download } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"

export default function ThreatIntelPage() {
  const handleExportReport = () => {
    const reportData = {
      title: "Threat Intelligence Report",
      generatedAt: new Date().toISOString(),
      platform: "Churchill Intelligence Platform",
      sections: {
        summary: "Real-time threat intelligence monitoring and analysis",
        threatActors: [
          { name: "APT28 (Fancy Bear)", campaigns: 47, riskScore: 98.5, origin: "Russia", lastSeen: "2 hours ago" },
          { name: "Lazarus Group", campaigns: 42, riskScore: 97.2, origin: "North Korea", lastSeen: "5 hours ago" },
          { name: "APT29 (Cozy Bear)", campaigns: 38, riskScore: 96.8, origin: "Russia", lastSeen: "1 day ago" },
          { name: "Carbanak", campaigns: 35, riskScore: 95.3, origin: "Eastern Europe", lastSeen: "3 days ago" },
          { name: "FIN7", campaigns: 31, riskScore: 94.1, origin: "Unknown", lastSeen: "1 week ago" },
        ],
        iocs: [
          { type: "IP Address", value: "192.168.1.100", threat: "C2 Server", severity: "Critical", matches: 847 },
          { type: "Domain", value: "malicious-site.com", threat: "Phishing", severity: "High", matches: 623 },
          { type: "File Hash", value: "a1b2c3d4e5f6...", threat: "Ransomware", severity: "Critical", matches: 512 },
          { type: "IP Address", value: "10.0.0.50", threat: "Botnet", severity: "High", matches: 389 },
        ],
        threatCategories: {
          malware: 2847,
          phishing: 1923,
          ransomware: 1456,
          apt: 892,
          zeroDay: 234,
        },
      },
    }

    // Convert to formatted text report
    const reportText = `
THREAT INTELLIGENCE REPORT
Generated: ${new Date().toLocaleString()}
Platform: Churchill Intelligence Platform - Live Feed

═══════════════════════════════════════════════════════════════

EXECUTIVE SUMMARY
${reportData.sections.summary}

═══════════════════════════════════════════════════════════════

TOP THREAT ACTORS

${reportData.sections.threatActors
  .map(
    (actor, i) => `
${i + 1}. ${actor.name}
   Risk Score: ${actor.riskScore}
   Active Campaigns: ${actor.campaigns}
   Origin: ${actor.origin}
   Last Seen: ${actor.lastSeen}
`,
  )
  .join("\n")}

═══════════════════════════════════════════════════════════════

INDICATORS OF COMPROMISE (IOCs)

${reportData.sections.iocs
  .map(
    (ioc, i) => `
${i + 1}. ${ioc.type}: ${ioc.value}
   Threat: ${ioc.threat}
   Severity: ${ioc.severity}
   Matches: ${ioc.matches}
`,
  )
  .join("\n")}

═══════════════════════════════════════════════════════════════

THREAT CATEGORIES DISTRIBUTION

Malware: ${reportData.sections.threatCategories.malware} incidents
Phishing: ${reportData.sections.threatCategories.phishing} incidents
Ransomware: ${reportData.sections.threatCategories.ransomware} incidents
APT: ${reportData.sections.threatCategories.apt} incidents
Zero-Day: ${reportData.sections.threatCategories.zeroDay} incidents

═══════════════════════════════════════════════════════════════

Report generated by VTS Command Center
Powered by Churchill Intelligence Platform
    `.trim()

    // Create and download the report
    const blob = new Blob([reportText], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.href = url
    link.download = `threat-intelligence-report-${new Date().toISOString().split("T")[0]}.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="flex h-screen">
      <SidebarNav />
      <div className="flex flex-1 flex-col overflow-hidden">
        <Header />
        <main className="flex-1 overflow-y-auto bg-background p-6">
          <div className="mb-8">
            <div className="flex items-start justify-between mb-2">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-gradient-to-br from-red-500/20 to-orange-500/20 border border-red-500/30">
                  <Shield className="h-6 w-6 text-red-500" />
                </div>
                <h1 className="text-3xl font-bold bg-gradient-to-r from-red-500 to-orange-500 bg-clip-text text-transparent">
                  Threat Intelligence
                </h1>
              </div>
              <Button
                onClick={handleExportReport}
                className="bg-gradient-to-r from-red-500 to-orange-500 hover:from-red-600 hover:to-orange-600 text-white font-semibold shadow-lg"
              >
                <Download className="h-4 w-4 mr-2" />
                Export Report
              </Button>
            </div>
            <p className="text-muted-foreground ml-14">
              Monitor threat actors, indicators of compromise, and emerging threats in real-time
            </p>
            <div className="ml-14 mt-3">
              <Badge className="text-sm font-semibold bg-cyan-500/20 text-cyan-400 border-cyan-500/50 px-4 py-1.5 hover:bg-cyan-500/30">
                <span className="inline-block w-2 h-2 rounded-full bg-cyan-400 mr-2 animate-pulse" />
                Powered by Churchill Intelligence Platform • Live Feed
              </Badge>
            </div>
          </div>

          <ThreatIntelStats />

          <div className="mt-8 grid gap-6 lg:grid-cols-2">
            <Card className="lg:col-span-2 border-red-500/20 bg-gradient-to-br from-background to-red-950/5">
              <CardHeader>
                <CardTitle className="text-xl">Cyber Threat Landscape</CardTitle>
              </CardHeader>
              <CardContent>
                <ThreatTrendsChart />
              </CardContent>
            </Card>

            <Card className="border-orange-500/20 bg-gradient-to-br from-background to-orange-950/5">
              <CardHeader>
                <CardTitle className="text-xl">Active Threat Categories</CardTitle>
              </CardHeader>
              <CardContent>
                <ThreatCategoriesChart />
              </CardContent>
            </Card>

            <Card className="border-purple-500/20 bg-gradient-to-br from-background to-purple-950/5">
              <CardHeader>
                <CardTitle className="text-xl">Active Threat Actors</CardTitle>
              </CardHeader>
              <CardContent>
                <ThreatActorsTable />
              </CardContent>
            </Card>

            <Card className="lg:col-span-2 border-blue-500/20 bg-gradient-to-br from-background to-blue-950/5">
              <CardHeader>
                <CardTitle className="text-xl">Indicators of Compromise</CardTitle>
              </CardHeader>
              <CardContent>
                <Tabs defaultValue="all">
                  <TabsList className="bg-muted/50">
                    <TabsTrigger value="all">All IOCs</TabsTrigger>
                    <TabsTrigger value="ip">IP Addresses</TabsTrigger>
                    <TabsTrigger value="domain">Domains</TabsTrigger>
                    <TabsTrigger value="hash">File Hashes</TabsTrigger>
                    <TabsTrigger value="url">URLs</TabsTrigger>
                  </TabsList>
                  <TabsContent value="all" className="mt-4">
                    <IOCTable filter="all" />
                  </TabsContent>
                  <TabsContent value="ip" className="mt-4">
                    <IOCTable filter="ip" />
                  </TabsContent>
                  <TabsContent value="domain" className="mt-4">
                    <IOCTable filter="domain" />
                  </TabsContent>
                  <TabsContent value="hash" className="mt-4">
                    <IOCTable filter="hash" />
                  </TabsContent>
                  <TabsContent value="url" className="mt-4">
                    <IOCTable filter="url" />
                  </TabsContent>
                </Tabs>
              </CardContent>
            </Card>
          </div>
        </main>
      </div>
    </div>
  )
}
