export const runtime = "nodejs"
export const dynamic = "force-dynamic"

export async function GET() {
  // Mock firmware data - in production, this would query the database
  const firmwareUpdates = [
    {
      id: "1",
      assetId: "cisco-r1",
      deviceName: "Cisco Router R1",
      vendor: "Cisco",
      currentVersion: "v15.2",
      latestVersion: "v15.9",
      status: "critical",
      riskScore: 95,
      cveIds: ["CVE-2025-1234", "CVE-2025-1235"],
      scheduledAt: null,
      appliedAt: null,
      downtimeEstimate: "30 minutes",
      releaseNotes: "Critical security patches for remote code execution vulnerabilities",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "2",
      assetId: "win-srv-01",
      deviceName: "Windows Server 2019",
      vendor: "Microsoft",
      currentVersion: "Build 19041",
      latestVersion: "Build 19045",
      status: "critical",
      riskScore: 92,
      cveIds: ["CVE-2025-5678"],
      scheduledAt: null,
      appliedAt: null,
      downtimeEstimate: "2 hours",
      releaseNotes: "Zero-day vulnerability patch - immediate update recommended",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "3",
      assetId: "ubnt-ap-01",
      deviceName: "Ubiquiti AP",
      vendor: "Ubiquiti",
      currentVersion: "6.1.2",
      latestVersion: "6.5.55",
      status: "critical",
      riskScore: 88,
      cveIds: ["CVE-2025-9012"],
      scheduledAt: null,
      appliedAt: null,
      downtimeEstimate: "15 minutes",
      releaseNotes: "RCE exploit active in the wild - urgent update required",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "4",
      assetId: "cisco-sw-01",
      deviceName: "Cisco Switch SW1",
      vendor: "Cisco",
      currentVersion: "v12.4",
      latestVersion: "v12.8",
      status: "outdated",
      riskScore: 65,
      cveIds: ["CVE-2024-8765"],
      scheduledAt: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
      appliedAt: null,
      downtimeEstimate: "45 minutes",
      releaseNotes: "Performance improvements and security enhancements",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "5",
      assetId: "palo-fw-01",
      deviceName: "Palo Alto Firewall",
      vendor: "Palo Alto",
      currentVersion: "10.1.3",
      latestVersion: "10.2.5",
      status: "outdated",
      riskScore: 70,
      cveIds: ["CVE-2024-4321"],
      scheduledAt: null,
      appliedAt: null,
      downtimeEstimate: "1 hour",
      releaseNotes: "Security updates for SSL/TLS vulnerabilities",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "6",
      assetId: "juniper-r1",
      deviceName: "Juniper Router",
      vendor: "Juniper",
      currentVersion: "20.4R1",
      latestVersion: "21.2R3",
      status: "outdated",
      riskScore: 55,
      cveIds: [],
      scheduledAt: null,
      appliedAt: null,
      downtimeEstimate: "30 minutes",
      releaseNotes: "Feature updates and bug fixes",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "7",
      assetId: "fortinet-fw",
      deviceName: "FortiGate Firewall",
      vendor: "Fortinet",
      currentVersion: "7.0.1",
      latestVersion: "7.2.4",
      status: "critical",
      riskScore: 85,
      cveIds: ["CVE-2025-3456"],
      scheduledAt: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
      appliedAt: null,
      downtimeEstimate: "1.5 hours",
      releaseNotes: "Critical authentication bypass vulnerability fixed",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "8",
      assetId: "dell-sw-01",
      deviceName: "Dell Switch",
      vendor: "Dell",
      currentVersion: "9.14.2.5",
      latestVersion: "9.14.2.10",
      status: "up-to-date",
      riskScore: 10,
      cveIds: [],
      scheduledAt: null,
      appliedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      downtimeEstimate: "20 minutes",
      releaseNotes: "Latest stable release",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ]

  return Response.json({ success: true, data: firmwareUpdates })
}
