export const runtime = "nodejs"
export const dynamic = "force-dynamic"

export async function GET() {
  // Mock vulnerability data - in production, query from database
  const vulnerabilities = [
    {
      id: "1",
      cve: "CVE-2024-1234",
      title: "Remote Code Execution in Apache",
      severity: "Critical",
      cvss: 9.8,
      affected: "Apache 2.4.x",
      status: "Open",
      discovered: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      category: "Web Apps",
      exploitAvailable: true,
      patchAvailable: true,
    },
    {
      id: "2",
      cve: "CVE-2024-5678",
      title: "SQL Injection in Web Application",
      severity: "High",
      cvss: 8.1,
      affected: "Custom App v3.2",
      status: "In Progress",
      discovered: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      category: "Web Apps",
      exploitAvailable: false,
      patchAvailable: true,
    },
    {
      id: "3",
      cve: "CVE-2024-9012",
      title: "Cross-Site Scripting Vulnerability",
      severity: "Medium",
      cvss: 6.5,
      affected: "Portal v2.1",
      status: "In Progress",
      discovered: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      category: "Web Apps",
      exploitAvailable: false,
      patchAvailable: false,
    },
    {
      id: "4",
      cve: "CVE-2024-3456",
      title: "Privilege Escalation in Linux Kernel",
      severity: "Critical",
      cvss: 9.3,
      affected: "Linux 5.15.x",
      status: "Open",
      discovered: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      category: "Endpoints",
      exploitAvailable: true,
      patchAvailable: true,
    },
    {
      id: "5",
      cve: "CVE-2024-7890",
      title: "Buffer Overflow in Network Service",
      severity: "High",
      cvss: 7.8,
      affected: "Network Daemon v1.4",
      status: "Patched",
      discovered: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      category: "Network",
      exploitAvailable: false,
      patchAvailable: true,
    },
    {
      id: "6",
      cve: "CVE-2024-2345",
      title: "Authentication Bypass",
      severity: "Critical",
      cvss: 9.1,
      affected: "Auth Service v2.0",
      status: "In Progress",
      discovered: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      category: "API",
      exploitAvailable: true,
      patchAvailable: false,
    },
    {
      id: "7",
      cve: "CVE-2024-6789",
      title: "Information Disclosure",
      severity: "Medium",
      cvss: 5.3,
      affected: "API Gateway v1.8",
      status: "Open",
      discovered: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
      category: "API",
      exploitAvailable: false,
      patchAvailable: true,
    },
    {
      id: "8",
      cve: "CVE-2024-4567",
      title: "Denial of Service Vulnerability",
      severity: "High",
      cvss: 7.5,
      affected: "Load Balancer v3.1",
      status: "Patched",
      discovered: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
      category: "Network",
      exploitAvailable: false,
      patchAvailable: true,
    },
    {
      id: "9",
      cve: "CVE-2024-8901",
      title: "Insecure Deserialization",
      severity: "Critical",
      cvss: 9.0,
      affected: "Java Application Server",
      status: "Open",
      discovered: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      category: "Web Apps",
      exploitAvailable: true,
      patchAvailable: false,
    },
    {
      id: "10",
      cve: "CVE-2024-1122",
      title: "Path Traversal Vulnerability",
      severity: "High",
      cvss: 8.2,
      affected: "File Server v2.3",
      status: "Open",
      discovered: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      category: "Endpoints",
      exploitAvailable: false,
      patchAvailable: true,
    },
    {
      id: "11",
      cve: "CVE-2024-3344",
      title: "XML External Entity Injection",
      severity: "High",
      cvss: 7.9,
      affected: "XML Parser v1.5",
      status: "In Progress",
      discovered: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      category: "API",
      exploitAvailable: false,
      patchAvailable: true,
    },
    {
      id: "12",
      cve: "CVE-2024-5566",
      title: "Weak Cryptography Implementation",
      severity: "Medium",
      cvss: 6.8,
      affected: "Encryption Library v3.0",
      status: "Open",
      discovered: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      category: "Database",
      exploitAvailable: false,
      patchAvailable: false,
    },
    {
      id: "13",
      cve: "CVE-2024-7788",
      title: "Server-Side Request Forgery",
      severity: "High",
      cvss: 8.5,
      affected: "Proxy Service v2.1",
      status: "Open",
      discovered: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
      category: "Network",
      exploitAvailable: true,
      patchAvailable: true,
    },
    {
      id: "14",
      cve: "CVE-2024-9900",
      title: "Command Injection Vulnerability",
      severity: "Critical",
      cvss: 9.5,
      affected: "CLI Tool v1.2",
      status: "Open",
      discovered: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      category: "Endpoints",
      exploitAvailable: true,
      patchAvailable: false,
    },
    {
      id: "15",
      cve: "CVE-2024-1010",
      title: "Race Condition in Session Handler",
      severity: "Medium",
      cvss: 6.2,
      affected: "Session Manager v4.0",
      status: "In Progress",
      discovered: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      category: "Web Apps",
      exploitAvailable: false,
      patchAvailable: true,
    },
    {
      id: "16",
      cve: "CVE-2024-2020",
      title: "Improper Access Control",
      severity: "High",
      cvss: 7.7,
      affected: "Admin Panel v2.5",
      status: "Open",
      discovered: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
      category: "Web Apps",
      exploitAvailable: false,
      patchAvailable: true,
    },
    {
      id: "17",
      cve: "CVE-2024-3030",
      title: "Memory Corruption Vulnerability",
      severity: "Critical",
      cvss: 9.2,
      affected: "Native Library v1.8",
      status: "In Progress",
      discovered: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
      category: "Endpoints",
      exploitAvailable: true,
      patchAvailable: true,
    },
    {
      id: "18",
      cve: "CVE-2024-4040",
      title: "Insecure Direct Object Reference",
      severity: "Medium",
      cvss: 6.0,
      affected: "REST API v3.1",
      status: "Open",
      discovered: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
      category: "API",
      exploitAvailable: false,
      patchAvailable: false,
    },
    {
      id: "19",
      cve: "CVE-2024-5050",
      title: "Unvalidated Redirects",
      severity: "Medium",
      cvss: 5.8,
      affected: "Web Portal v2.0",
      status: "Patched",
      discovered: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      category: "Web Apps",
      exploitAvailable: false,
      patchAvailable: true,
    },
    {
      id: "20",
      cve: "CVE-2024-6060",
      title: "Broken Authentication Mechanism",
      severity: "Critical",
      cvss: 9.4,
      affected: "SSO Service v1.0",
      status: "Open",
      discovered: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
      category: "API",
      exploitAvailable: true,
      patchAvailable: true,
    },
    {
      id: "21",
      cve: "CVE-2024-7070",
      title: "Insufficient Logging & Monitoring",
      severity: "Medium",
      cvss: 5.5,
      affected: "Logging Service v2.2",
      status: "Open",
      discovered: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
      category: "Cloud",
      exploitAvailable: false,
      patchAvailable: false,
    },
    {
      id: "22",
      cve: "CVE-2024-8080",
      title: "Use of Hard-coded Credentials",
      severity: "High",
      cvss: 8.0,
      affected: "IoT Device Firmware v1.1",
      status: "In Progress",
      discovered: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
      category: "Mobile",
      exploitAvailable: true,
      patchAvailable: true,
    },
    {
      id: "23",
      cve: "CVE-2024-9090",
      title: "Missing Encryption of Sensitive Data",
      severity: "High",
      cvss: 7.6,
      affected: "Database Connector v3.3",
      status: "Open",
      discovered: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
      category: "Database",
      exploitAvailable: false,
      patchAvailable: true,
    },
  ]

  // Calculate statistics
  const stats = {
    total: vulnerabilities.length,
    critical: vulnerabilities.filter((v) => v.severity === "Critical").length,
    high: vulnerabilities.filter((v) => v.severity === "High").length,
    medium: vulnerabilities.filter((v) => v.severity === "Medium").length,
    low: vulnerabilities.filter((v) => v.severity === "Low").length,
    open: vulnerabilities.filter((v) => v.status === "Open").length,
    inProgress: vulnerabilities.filter((v) => v.status === "In Progress").length,
    patched: vulnerabilities.filter((v) => v.status === "Patched").length,
    exploitAvailable: vulnerabilities.filter((v) => v.exploitAvailable).length,
  }

  // Calculate distribution by category
  const distribution = vulnerabilities.reduce(
    (acc, vuln) => {
      if (!acc[vuln.category]) {
        acc[vuln.category] = { total: 0, critical: 0, high: 0, medium: 0, low: 0 }
      }
      acc[vuln.category].total++
      acc[vuln.category][vuln.severity.toLowerCase()]++
      return acc
    },
    {} as Record<string, any>,
  )

  return Response.json({
    success: true,
    data: {
      vulnerabilities,
      stats,
      distribution,
    },
  })
}
