import { NextResponse } from "next/server"

export async function GET() {
  // Mock AI assets data
  const assets = [
    {
      id: "1",
      name: "GPT-4",
      asset_type: "LLM",
      provider: "Azure ML",
      cloud: "Azure",
      environment: "Production",
      risk_score: 72,
      assets_discovered: 3,
      runtime_protection: false,
      risks: 2,
      top_risk: "Prompt Injection (OWASP LLM01)",
      status: "Active",
      attempts: 12,
      timestamp: new Date(),
    },
    {
      id: "2",
      name: "Customer Support Bot",
      asset_type: "LLM",
      provider: "OpenAI",
      cloud: "OpenAI",
      environment: "Production",
      risk_score: 65,
      assets_discovered: 10,
      runtime_protection: true,
      risks: 1,
      top_risk: "Insecure Output Handling (OWASP LLM02)",
      status: "Active",
      attempts: 8,
      timestamp: new Date(),
    },
    {
      id: "3",
      name: "Training Dataset",
      asset_type: "Dataset",
      provider: "S3 Bucket",
      cloud: "AWS",
      environment: "Production",
      risk_score: 88,
      assets_discovered: 5,
      runtime_protection: false,
      risks: 3,
      top_risk: "Publicly Writable (Critical)",
      status: "Active",
      attempts: 24,
      timestamp: new Date(),
    },
    {
      id: "4",
      name: "Pinecone Vector DB",
      asset_type: "VectorDB",
      provider: "Pinecone",
      cloud: "GCP",
      environment: "Production",
      risk_score: 54,
      assets_discovered: 2,
      runtime_protection: true,
      risks: 1,
      top_risk: "Data Leakage Risk",
      status: "Active",
      attempts: 5,
      timestamp: new Date(),
    },
    {
      id: "5",
      name: "LangChain Pipeline",
      asset_type: "Pipeline",
      provider: "Custom",
      cloud: "AWS",
      environment: "Development",
      risk_score: 45,
      assets_discovered: 8,
      runtime_protection: true,
      risks: 2,
      top_risk: "Supply Chain Vulnerability",
      status: "Active",
      attempts: 3,
      timestamp: new Date(),
    },
  ]

  return NextResponse.json({ assets })
}
